[package]
name = "day-01-rust"
version = "0.1.0"
authors = ["Alexandru Dinu <alex.dinu07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
